version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
  test-cases:
    working_directory: ~/opt/report/
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout:
          path: ~/opt
      - run: 
          name: Installing prerequisites
          command: |-
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6DB5542C356545CF # Adding Heroku keys, else the apt update will fail.
            sudo apt-get update && sudo apt install -y ca-certificates libxpm4 libxrender1 libgtk2.0-0 libnss3 libgconf-2-4 \
                  xvfb gtk2-engines-pixbuf \
                  xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable
            curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            sudo apt install nodejs -y
            sudo npm install -g yarn
            node --version
      - restore_cache:
          name: Restoring cache
          key: dependency-cache-portal-{{ checksum "package.json" }}
      - run:
          name: Installing npm deps
          command: 'npm install'
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-portal-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Executing test cases
          command: 'npm run test | tee /tmp/logs/test_cases.log'
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-cases